### ISSUE TITLE
Question: Listening to changes

### ISSUE THREAD

**Issue by betov75** [RomeoDespres/reapy#100]
Hi! What is the best way to continuously listen to Reaper's changes while not overloading it? Do I loop the with inside_reaper in a thread? How do I listen to a track change, for example? Thanks!

**Comment by RomeoDespres** [comment]
Hi, there's no native way to listen to changes in the reaper API. Do you run your scripts inside or outside reaper? In the first case, you can use [`reapy.defer`](https://python-reapy.readthedocs.io/en/latest/api_guide.html#non-blocking-loops-inside-reaper-with-reapy-defer-and-reapy-at-exit) to avoid blocking the interface:

```python
import reapy


def maybe_do_stuff(track, previous_name):
    if track.name != previous_name:
        do_stuff()
    reapy.defer(maybe_do_stuff, track, track.name)

track = reapy.Project().tracks[0]
name = track.name
maybe_do_stuff(track, name)
```

 In the second case, REAPER always waits a little bit before executing a reapy call to avoid freezing the UI. Thus you can simply do:

```python
import reapy

track = reapy.Project().tracks[0]
name = track.name
while True:
    new_name = track.name
    if new_name != name:
        do_stuff()
    name = new_name
```

You can then wrap this basic logic in a better interface with an "event loop" feel if you have a lot of different variables to monitor.

**Comment by betov75** [comment]
Hi Romeo,
Thank you very much for your answer, that's exactly the behavior I wanted
to get from Reaper. I really don't need speed since it only detects the
changed track. I mostly use Reapy to send things, not receive. But with
OSC, really strange thing, Reaper don't send info about banks so i'm unable
to use a single fader... Very limiting. So, even if Reapy only gets the
refresh 10 times a second, no trouble there.
That said, will that loop slow down Reaper when launched from outside?
Thanks again!

Le sam. 31 oct. 2020 à 12:45, Roméo Després <notifications@github.com> a
écrit :

**Comment by RomeoDespres** [comment]
Glad if it helps! The loop outside Reaper will very marginally slow down Reaper, but it's not something you should feel.

**Comment by betov75** [comment]
Thank you very much. Your code is so elegant in the module. Cuckos must hire you to rethink the API. :) BTW, I will only use a 0.5 second loop interval to reaper, I don't expect that to slow down anything according to my tests so, great!
