### ISSUE TITLE
module 'reapy.reascript_api' has no attribute xxx

### ISSUE THREAD

**Issue by Narthe** [RomeoDespres/reapy#103]
Hello,
i'm trying to setup reapy on my machine.
When using this command in a console : `python -c "import reapy; reapy.configure_reaper()"` i get the warning that it can't reach the distant API and that Reaper isn't started (even though it is).
I then tried to call `reapy.config.enable_dist_api()` from inside Reaper but realized it was deprecated so i tried `reapy.config.configure_reaper()` and got this :
```python
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    reapy.config.configure_reaper()
  File "F:\Python38_64\lib\site-packages\reapy\config\config.py", line 210, in configure_reaper
    resource_path = get_resource_path(detect_portable_install)
  File "F:\Python38_64\lib\site-packages\reapy\config\resource_path.py", line 60, in get_resource_path
    for dir in get_candidate_directories(detect_portable_install):
  File "F:\Python38_64\lib\site-packages\reapy\config\resource_path.py", line 16, in get_candidate_directories
    yield get_portable_resource_directory()
  File "F:\Python38_64\lib\site-packages\reapy\config\resource_path.py", line 26, in get_portable_resource_directory
    process_path = get_reaper_process_path()
  File "F:\Python38_64\lib\site-packages\reapy\config\resource_path.py", line 47, in get_reaper_process_path
    p for p in psutil.process_iter(['name', 'exe'])
NameError: name 'psutil' is not defined
```

I think you're trying to use psutil but it wasn't imported because `reapy.is_inside_reaper()` returned True at line 9 of config.py.

I guess reapy is still not configured correctly because when i try things like `reapy.print("Hello world!")` i get this : `AttributeError: module 'reapy.reascript_api' has no attribute 'ShowConsoleMsg'`

A few precisions : I'm using a portable evaluation license of Reaper, if that matters. I'm using Python 3.8.0 64 bits and i'm on a machine at work protected by a company proxy.

Thank you.

**Comment by dimentorium** [comment]
Hello NArthe,
have you enabled everything inside Reaper? So enabling the distant API that it can communicate with your Python environment?
You can check here https://dimentorium.wixsite.com/raipt/post/reapy-python-module

**Comment by RomeoDespres** [comment]
Hi all, indeed it looks like you tried to run  `configure_reaper` from inside REAPER rather than from a standard Python shell.

By the way @dimentorium, it would be great if you updated your blog post with the new configuration process (see the README for details), especially because it should work much better on OSX and Linux.

**Comment by Narthe** [comment]
@dimentorium : I'm getting those errors while trying to enable the distant API as described in the reapy documentation. I read your blog post but as @RomeoDespres mentions, it feels like it's not up to date, there is no "enable_distant_api" script to load in the action list and run.

**Comment by RomeoDespres** [comment]
Hey @Narthe, may seem stupid but I just have to make sure it is off the table. Have you closed and restarted REAPER after calling `reapy.configure_reaper()`?

**Comment by Narthe** [comment]
Yes i did

**Comment by RomeoDespres** [comment]
Ok thank you. I'm not sure yet of what's behind this so if you're ok with it, I'd appreciate some help from you for debugging.

Could you please do the following:

1. Open REAPER.
2. Open Preferences (*Options* > *Preferences...* or Ctrl+P / Cmd + P), then scroll down in the left pane to *Control/OSC/web* and select it. Please post a screenshot of what's displayed in the right pane.
3. Open a Python shell, run the following lines and please post the output:
```python
import reapy
import sys

print(f'reapy.is_inside_reaper: {reapy.is_inside_reaper()}')
print(f'Main module has "obj" attribute: {hasattr(sys.modules["__main__"], "obj")}')
print(f'Selected host is: {reapy.tools.network.machines.get_selected_machine_host()}')
```

**Comment by Narthe** [comment]
I'd be happy to help. This is the screenshot of the control/osc/web tab
![image](https://user-images.githubusercontent.com/1123343/98740849-b59e5680-2379-11eb-82c3-408246c5b261.png)

and this is the output of the snippet code you provided :
```python
F:\dev\reaper_trimmer> F:\Python38_64\python.exe .\test.py
F:\Python38_64\lib\site-packages\reapy\tools\network\machines.py:99: DisabledDistAPIWarning: Can't reach distant API. Please start REAPER, or call reapy.config.enable_dist_api() from inside REAPER to enable distant API.
  warnings.warn(errors.DisabledDistAPIWarning())
reapy.is_inside_reaper: False
Main module has "obj" attribute: False
Selected host is: None
```

**Comment by RomeoDespres** [comment]
Ok thanks. So the issue doesn't come from where I thought it would. Maybe there's something wrong with this proxy you've mentioned, so let's investigate that now. Can you please try the following, with REAPER open:

1. Visit `http://localhost:2307/` in your browser. Do you see the REAPER control page with the kind of controls below?

![image](https://user-images.githubusercontent.com/39157756/98794013-dcf03480-2408-11eb-86de-84a6be1be1d0.png)

2. If you visit `http://localhost:2307/_/GET/EXTSTATE/reapy/activate_reapy_server` and `http://localhost:2307/_/GET/EXTSTATE/reapy/server_port`, what do you get?

3. Please post the output of the following snippet:

```python
import time
import urllib

host = 'localhost'

for key in 'activate_reapy_server', 'server_port':
    for timeout in 0.5, None:
        try:
            url = f'http://{host}:2307/_/GET/EXTSTATE/reapy/{key}'
            print(url, timeout)
            start_time = time.time()
            print(f'{urllib.request.urlopen(url, timeout=timeout).read().decode("utf-8")}({time.time() - start_time:.2f} s.)')
        except Exception as e:
            print(f'{repr(e)} ({time.time() - start_time:.2f} s.)')
```

**Comment by Narthe** [comment]
1. Yes i see it
2. I get this : `EXTSTATE	reapy	activate_reapy_server	"_RSHyCKrjRPrtNZyWM0rIWPnFcHxsVTGqM7J919DVhg"`
3. Output of the snippet :
```python
http://localhost:2307/_/GET/EXTSTATE/reapy/activate_reapy_server 0.5
AttributeError("module 'urllib' has no attribute 'request'") (0.00 s.)
http://localhost:2307/_/GET/EXTSTATE/reapy/activate_reapy_server None
AttributeError("module 'urllib' has no attribute 'request'") (0.00 s.)
http://localhost:2307/_/GET/EXTSTATE/reapy/server_port 0.5
AttributeError("module 'urllib' has no attribute 'request'") (0.00 s.)
http://localhost:2307/_/GET/EXTSTATE/reapy/server_port None
AttributeError("module 'urllib' has no attribute 'request'") (0.00 s.)
```

**Comment by RomeoDespres** [comment]
Sorry my mistake, I've been running those with IPython which (I don't know why) automatically imports urllib.request.

I've edited it a bit to include more information, could you please retry:

```python
import time
from urllib import request


host = 'localhost'
action_id = '_RSHyCKrjRPrtNZyWM0rIWPnFcHxsVTGqM7J919DVhg'


def fetch(url, twice=True):
    timeouts = ([.5] if twice else []) + [None]
    for timeout in timeouts:
        try:
            print(url, timeout)
            start_time = time.time()
            print(request.urlopen(url, timeout=timeout).read().decode('utf-8'), end='')
        except Exception as e:
            print(repr(e), end=' ')
        finally:
            print(f'({time.time() - start_time:.2f} s.)')


fetch(f'http://{host}:2307/_/GET/EXTSTATE/reapy/activate_reapy_server')
fetch(f'http://{host}:2307/_/GET/EXTSTATE/reapy/server_port')
fetch(f'http://{host}:2307/_/{action_id}', twice=False)
fetch(f'http://{host}:2307/_/GET/EXTSTATE/reapy/server_port')
```

**Comment by Narthe** [comment]
I guessed it was not the expected output but i didn't want to mess up your code =P
Here is the output with the latest snippet :
````python
http://localhost:2307/_/GET/EXTSTATE/reapy/activate_reapy_server 0.5
<HTTPError 502: 'cannotconnect'> (0.04 s.)
http://localhost:2307/_/GET/EXTSTATE/reapy/activate_reapy_server None
<HTTPError 502: 'cannotconnect'> (0.01 s.)
http://localhost:2307/_/GET/EXTSTATE/reapy/server_port 0.5
<HTTPError 502: 'cannotconnect'> (0.02 s.)
http://localhost:2307/_/GET/EXTSTATE/reapy/server_port None
<HTTPError 502: 'cannotconnect'> (0.01 s.)
http://localhost:2307/_/_RSHyCKrjRPrtNZyWM0rIWPnFcHxsVTGqM7J919DVhg None
<HTTPError 502: 'cannotconnect'> (0.01 s.)
http://localhost:2307/_/GET/EXTSTATE/reapy/server_port 0.5
<HTTPError 502: 'cannotconnect'> (0.01 s.)
http://localhost:2307/_/GET/EXTSTATE/reapy/server_port None
<HTTPError 502: 'cannotconnect'> (0.01 s.)
```

**Comment by RomeoDespres** [comment]
Thanks, finally something that doesn't work as expected!

I'm not sure yet but I guess you could try the following:

```bash
py -c "import os; os.environ['no_proxy'] = 'localhost'; import reapy; reapy.print('hey :)')"
```

**Comment by Narthe** [comment]
It works
![image](https://user-images.githubusercontent.com/1123343/98855877-be9b3080-242a-11eb-9e74-8fbf515b5438.png)

**Comment by RomeoDespres** [comment]
Great! I'm not sure yet if this should be included in reapy by default, or be a customizable option, or if it's too specific and you should just go with adding this environment variable patch before any script you run... I'll think more on that. In any case I'll have to add this to the documentation.

By the way if it's something your company allows you to do, you can also check your proxy settings and set up an exception for localhost. Below is the Windows version of it:

![image](https://user-images.githubusercontent.com/39157756/98856651-29b22a80-245e-11eb-9180-a4f3eea508b3.png)

**Comment by Narthe** [comment]
I tried to setup the proxy in windows settings as you suggested but i can't get it to work so i guess i'll go with your initial solution.
Thanks a lot for your help and the time you spent on it.

**Comment by FelixKarlheinz** [comment]
Hey coming in a little late :), I have the same issue (same outputs as Narthe)  but neither setting the env variable nor the proxy resolves that I can control Reaper from the outside... Do you have any other suggestions what could be wrong? Best Felix

**Comment by jbps24** [comment]
@FelixKarlheinz Hey! I'm a bit late. I have had the same issue after reinstalling my repo to another directory (using conda!). the reapy.configure_reaper() only works the first time, when you use a conda env. 

To resolve this, I have deleted the reaper.ini file. After that and a Reaper restart it worked again. (But also resets all settings in Reaper)

Maybe someone can find the entry that causes this...
