### ISSUE TITLE
Fx parameters value string

### ISSUE THREAD

**Issue by betov75** [RomeoDespres/reapy#125]
Hi!
Is it possible to retrieve the value string of a parameter?
I can get the name, the value float but the plugin also sends a string with a textual value. For example,. BBC SO Vst Expression parameter's value string is 0-100%. Some others are in 'Hz', etc..
Thanks!

**Comment by Levitanus** [comment]
```Python
import reapy as rpr

pr = rpr.Project()
track = pr.selected_tracks[0]
fx = track.fxs[0]
param = fx.params['Wet']

print(param.formatted)
```

**Comment by betov75** [comment]
That's perfect.
Thank you very much for your quick reply!
Have a great day.
