### ISSUE TITLE
sws api is missing

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#15]
reapy imports only reaper_python module, still many functions (within installed SWS) are placed inside sws_python module.
It includes all reaper_python functions

I've tried to locate the import statement of the client (inside reaper), but haven't got success...
Tried to import sws_python inside reascript_api module, but it doesn't work...
The distant API seemed to have all functions from SWS repository wrapped.

**Comment by RomeoDespres** [comment]
Since [Version 0.3.0](https://github.com/RomeoDespres/reapy/releases/tag/0.3.0), SWS functions are available in `reapy.reascript_api` if the extension is installed.
