### ISSUE TITLE
optimize reascript autogenerated API for jedi parcing

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#16]
Now my Jedi completion does not see autogenerated API.
But, I think it's not so hard to change, within, maybe moving some imports at the start of files?

**Comment by RomeoDespres** [comment]
Since [version 0.3.0](https://github.com/RomeoDespres/reapy/releases/tag/0.3.0), `reapy_generated_api.py` is stored in the user's `site-packages` directory. On my computer at least, this allows Jedi to autocomplete ReaScript functions. You could try to upgrade `reapy` (`pip install --upgrade python-reapy`) and see if it works better. Note that you will have to import it from outside REAPER at least once (so that it creates `reapy_generated_api.py`).

**Comment by RomeoDespres** [comment]
Hi, did you get the chance to try it?

**Comment by Levitanus** [comment]
Hi, sorry, it has failed, but I was too lazy for producing the structured output...

![reapy api](https://user-images.githubusercontent.com/29713891/58030493-d7ce6400-7b48-11e9-8cb8-db3912c3fb3b.gif)

Honestly, I really can't understand where the problem is. Maybe Jedi recursion level tuned not enough.
I still can't tune separate jedi completion for ST3, so using one from Anaconda package, which isn't tunable at all.

**Comment by Levitanus** [comment]
```C:\Users\Levitanus>pip install python-reapy
Requirement already satisfied: python-reapy in c:\users\levitanus\appdata\local\programs\python\python37-32\lib\site-packages (0.3.0)

C:\Users\Levitanus>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import reapy
C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\reapy\tools\dist_program.py:14: DisabledDistAPIWarning: Can't reach distant API. Please start REAPER, or call reapy.config.enable_dist_api() from inside REAPER to enable distant API.
  warnings.warn(DisabledDistAPIWarning())
>>> from reapy import reascript_api
>>> exit()```

**Comment by Levitanus** [comment]
Ahhh, I'm very sorry... It had to be registered in reaper within new version.
Now it works, thanks!

**Comment by RomeoDespres** [comment]
Great to know it! Thanks for the feedback! :)

**Comment by Levitanus** [comment]
As I understand, no possible to make such "completion-friendly" api now?
At least, now I don't see any sign of something like reapy_generated_api.py
