### ISSUE TITLE
where reapy.MIDINoteNames leads to?

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#36]
making stub files for mypy and cannot reveal the type of them. Maybe, I can also fix the missing, if they are)

**Comment by Levitanus** [comment]
marked as list of str. am I right?

**Comment by Levitanus** [comment]
```
    @property
    def midi_note_names(self):
        names = [RPR.GetTrackMIDINoteName(self.id, i, 0) for i in range(128)]
        return names
```
m?

**Comment by RomeoDespres** [comment]
Looks like that's what they are, even though I haven't really used this `GetTrackMIDINoteName` function before!...
