### ISSUE TITLE
retriveing of audio data from outside of reaper

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#37]
during my last experience with reapy (last spring, I think), I found that retriveing of audio data through socket is almost impossible because of timeouts.
Considering this I want to suggest reaper-independed import of source.
I'm going to make small help-lib with usage of librosa as audio accessing and analysing tool, and, if You don't mind, I can implement it as part of reapy package, for example, by extending of item sub-package.

But this solution has quite remarkable contra: adding dependecy of heavy librosa (which depends on numpy and scipy) to the reapy package.
But, also, librosa has a great advantage of loading audio within resampling and seeking inside with float time, which takes off a tone of support code, needed for working with raw wave data got from Reaper.

So I need your feedback on this idea and, maybe, will look to other variants, pointed by you.

**Comment by RomeoDespres** [comment]
This is interesting. Indeed, a depency to `librosa` is something I would rather avoid if possible. `reapy` has no dependencies so far, and it would be a shame to include such a big for only one feature... Yet it is obviously important to be able to deal with audio when using REAPER so maybe we'll have to do it. Before that, I would like to explore whether it is really needed. Could you please post an example of code that results in errors?

**Comment by RomeoDespres** [comment]
Have you eventually found a solution, or any follow-up questions, about this one?

**Comment by Levitanus** [comment]
Pity, but I've frozen the idea until solve the simplest problem of replacement VEPro under the Linux...
I will, definitely, come back to this task, but now it's totally out of close-by plans...

**Comment by RomeoDespres** [comment]
No worries. I'll close this one for now, and when/if you encounter new issues feel free to open a new one.
