### ISSUE TITLE
Inserting a wav file in a track/item/take.

### ISSUE THREAD

**Issue by aelimame** [RomeoDespres/reapy#38]
Hi,

I'm trying to use the library to add a wav from an actual wave file on my disk to a track in a Reaper project.

I tried using the following steps: 
1. Create a new track. new_track = proj.add_track(..)
2. Add a new item. new_item = new_track.add_item(..)
3. Add a new take. new_take = new_item.add_take(..)
4. Finally associate my wave file name to new_take.source.filename.

The last step does not seem to work (1 to 3 work fine and I can see the results live in the Reaper project). I checked the reapy.core.item.take and reapy.core.item.source code and I can see that 
Take.source and Source.filename are "read only" properties so they cannot be set.

I tried using the native reascript_api calls to try and initialize a new source with my_wave_filename.
1. my_src_id = RPR.PCM_Source_CreateFromFile(my_wave_filename)
2. RPR.SetMediaItemTake_Source(new_take.id, my_src_id)

This does nothing and the take source file does not change in the Reaper project.

I tried setting an already available source from another track/item/take and it works juste fine.
This seems to me like the reascript_api calls (specifically PCM_Source_CreateFromFile() ) do not work as expected.

Any thoughts?

**Comment by chabErch** [comment]
Hi, @aelimame
This is a [Reaper bug](https://forum.cockos.com/showthread.php?t=191871&highlight=RPR_SetMediaItemTake_Source), not reapy\`s. 
To setting source to media item you need to use [SWS extension](http://www.sws-extension.org/) (specifically BR_SetTakeSourceFromFile() function).

```python
from reapy import reascript_api as reaper


CURRENT_PROJECT = 0
FILE_NAME = r"C:\Audio.mp3"


reaper.InsertTrackAtIndex(0, False)
track = reaper.GetTrack(CURRENT_PROJECT, 0)

item = reaper.AddMediaItemToTrack(track)
reaper.SetMediaItemLength(item, 100, False)

take = reaper.AddTakeToMediaItem(item)
source = reaper.PCM_Source_CreateFromFile(FILE_NAME)
reaper.BR_SetTakeSourceFromFile(take, FILE_NAME, False)

reaper.UpdateArrange()
reaper.Main_OnCommand(40048, 0)  # Peaks: Rebuild all peaks
```

**Comment by aelimame** [comment]
Hi @chabErch,

Thank you for your response. Ok that explains why when I use an already available source from another track/item/take it works just fine.

I also found-out that I can use the : RPR_InsertMedia() call to directly inset a wave file in the currently selected track. So with the following code I wav able to do what I was looking for: 

```python
from reapy import reascript_api as RPR

my_wave_filename = "C:\my_wave_file.wav"

proj = reapy.Project()
new_track = proj.add_track(name='New Track')
new_track.select()
proj.cursor_position = 60 # Insert at 60 sec
succ = RPR.InsertMedia(my_wave_filename, 0)

```
