### ISSUE TITLE
access reapy server through network

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#41]
As I understand there is no really difference in connection to localhost or, for example, to 192.168.0.2:2307.
Can it be implemented as use-case? Now I see solution in extraction IP to the ```config.py``` as well as ```WEB_INTERFACE_PORT```, and reassigning at need. But I'm not sure in consequences of just this extraction: Could for example couple of scripts work together with different IP?)

**Comment by RomeoDespres** [comment]
I'm sorry but I don't understand your question... What feature would you like to see implemented exactly, and why?

**Comment by Levitanus** [comment]
I want to control other reapers in local network (slave machines), still, as reapy is already works through sockets I don't see any reason to make another socket layer for my own scripts.
Ideally, I would like to write somsing like this:
```Python
with inside_reaper('192.168.0.2:2307'):
    do_slave_action()```
But the option with, for example such mechanic also is cool:
```Python
reapy.config.WEB_INTERFACE_IP = '192.168.0.2'
do_slave_action()
```
Still, this is not the only case, it also can be extremely useful in making custom control surface for iOs\Android with kite, for example.

**Comment by RomeoDespres** [comment]
I see now, it makes total sense! I'll try to work on it soon. The only difficulty is that I don't have any slave machine at home so I won't really be able to test features... If you're ok though, you may help me by downloading the feature branch I'll make and test it yourself.

**Comment by RomeoDespres** [comment]
Hi again, I have pushed a [new branch](https://github.com/RomeoDespres/reapy/tree/feature/slave-machines) that implements the feature you asked for. As I mentioned in my last post, I only have one computer at hand which prevents me from really testing it. So if you are still interested, please download the new branch and give it a try :)

All machines (master and slaves) you want to use should have the branch version of reapy installed. The new function is called `reapy.connect` and you should be able to use it as such:

```python
reapy.connect('192.168.0.2')
do_stuff_on_slave_machine()
reapy.connect('localhost')
do_stuff_on_local_machine()

# OR

with reapy.connect('192.168.0.2'):
    do_stuff_on_slave_machine()
do_stuff_on_local_machine()
```

Feel free to ask any questions and report all the bugs you will probably have!

**Comment by Levitanus** [comment]
thanks a lot!
I will try this week.

**Comment by RomeoDespres** [comment]
Hi again :) Have you had the opportunity to try this feature?

**Comment by Levitanus** [comment]
I'm really sorry for the late answer!!! Was really bothered by live perf...
Finally, I've migrated my server PC to the ubuntu and made the basic setup: Reaper\python\reapy, which is accessible from the master PC without any problems as I can see.
At the moment my projecct still relays on my own TCP\UDP sockets, but I can wait to try migrate to the reapy built-in funcs and test them.

Don't really know if the issue should be closed now, as I have not tested it deep yet. But, maybe it's reasonable to left the rest on the future issues.

Thanks a lot!

**Comment by RomeoDespres** [comment]
No worry :) I think it is okay to leave it open until the feature has been pushed to `master`.

**Comment by Levitanus** [comment]
I'm really sorry, asking this here, but I could not find the way to direct PM.
I don't have experience in team developement with git. So, now, I'm having troubles with contributing to the repository:

* first of all, my github fork somehow missing newely created branches, so, for diving into the particular branch forced to reforking the repository. I've found something about this issue, and, hope will try to avoid it in future
* now I'm bothered much more in the overall workflow organization: for example, if I want to use the new connect feature I'm attempted to use this branch, but if I want to fix something in my type hints, commited before to the master — I have to switch local repo into the master, make changes, commit, and, switching back I'm still with lacking type hints because the changes made in the separate branch. And I cannot feel good with making the same changes into the "slave-machines" branch. as it can produce merge conflicts. How to manage such things?
* Also, I'm having problems in testing changes, as they will work under the clean pip installation. As I understand, some sort of CI is the sort of solution, but it looks like a quite overhead
* finally, I'm not sure about making some small-fixes into the main codebase. Should it be the separated feature branch, or it is OK to make changes directly at master and then pull into your repo?

I understand these are noob questions, but I don't have anyone possible to discuss this at my backyard...

**Comment by Levitanus** [comment]
missclick...
Here the right place:
In case of connecting to localhost with disabled Reaper web interface, import and connect() raises the DistAPIError

But, in case of connecting to the slave machine — not, because of using `socket._GLOBAL_DEFAULT_TIMEOUT` inside of urllib.
My hotfix of `reapy.web_interface.ExtState` works, as I see, but I can't imagine the consequences of such timeout seting.
```Python
class ExtState:
    def __init__(self, web_interface):
        self._url = web_interface._url + "{method}/EXTSTATE/reapy/{key}"

    def __getitem__(self, key):
        url = self._url.format(method="GET", key=key)
        string = request.urlopen(url, timeout=.5).read().decode("utf-8")
        value = string.split("\t")[-1][:-1]
        if not value:
            raise UndefinedExtStateError(key)
        value = json.loads(value)
        return value
```

Also, I don't think, that connect should throw warning on fail, It's quite a trick to catch a warning, but much more verbose to fail on exception.

**Comment by Levitanus** [comment]
ahh, now I see:
if reapy is imported within shutdowned local reaper, there also will be exception, which is not the disared behaviour for, for example, android front-end, which doesn't have reaper in localhost...

I'll think on this use-case

**Comment by RomeoDespres** [comment]
About your questions regarding git: sadly I'm not an expert with it either... I'm trying to do things in a clean fashion but honestly I'm just as noob as you... (or actually more! Your commit descriptions are so much more organized and helpful than mine, I definitely have to get as good as you on this point)
