### ISSUE TITLE
unable to add MIDI notes

### ISSUE THREAD

**Issue by d-vyd** [RomeoDespres/reapy#43]
Hi Romeo,
I'm really excited about your Pythonic interface to Reaper! This issue is probably user error but I'm not sure where to post my question. I'm able to add tracks, items, and takes--but not MIDI notes with this code, which I expected to add 8 notes:
```
# load Reaper library/API
import reapy
from random import randint as r

# connect to current project
project = reapy.Project()

# add a new track, item, take, and notes
track = project.add_track(name="drums")
item = track.add_midi_item(start=0,end=2)
take = item.add_take()
for n in range(0,8):
    take.add_note(start=n,end=n+0.1,pitch=r(0,127),channel=1,unit="beats")
```

**Comment by RomeoDespres** [comment]
Hi,

`Item.add_take()` creates an audio take and not a MIDI one, which is why your notes are not added to it. If you replace `take = item.add_take()` by `take = item.active_take` (which is a MIDI take since `item` is a MIDI item), your code should work.

**Comment by d-vyd** [comment]
Great! Thank you!

On Nov 16, 2019 3:48 PM, RomeoDespres <notifications@github.com> wrote:

Hi,

Item.add_take() creates an audio take and not a MIDI one, which is why your notes are not added to it. If you replace take = item.add_take() by take = item.active_take (which is a MIDI take since item is a MIDI item), your code should work.
