### ISSUE TITLE
SWS functions not working

### ISSUE THREAD

**Issue by timpauli** [RomeoDespres/reapy#51]
Hi,

first of all thanks for creating reapy it is of great use.

I installed the SWS Extension sucessfully. (The menus show up under Extensions)

But when I try to use them from outside with python I get errors:
```
from reapy import reascript_api as rpr

FILE_NAME = "YOUR AUDIO FILE"
rpr.InsertTrackAtIndex(0, False)
track = rpr.GetTrack(0, 0)
item = rpr.AddMediaItemToTrack(track)
rpr.SetMediaItemLength(item, 1, False)
take = rpr.AddTakeToMediaItem(item)
rpr.BR_SetTakeSourceFromFile(take, FILE_NAME, False)
rpr.UpdateArrange()
```
throws
```
AttributeError: module 'reapy.reascript_api' has no attribute 'BR_SetTakeSourceFromFile'
```

I am on Ubuntu 19.10 what could be the problem?

Thank you very much
Best
Tim

**Comment by RomeoDespres** [comment]
Hi! Glad to hear we have Linux users here :) I don't have REAPER for Linux myself so it may be a bit hard to help you, but maybe you can try help me understand what's wrong. First, do you get an error when you run the following from inside REAPER (with a normal ReaScript)?

```python
import sws_python
```

**Comment by timpauli** [comment]
ah okay. I get `ModuleNotFoundError: No module named 'sws_python'`
So I think something is wrong with the sws setup.
I am on SWS version 2.11.0.0 08d3c6fc pre-release build
Maybe that is part of the problem?
I just could not find an sws build for linux of the current stable release on the internet.

**Comment by RomeoDespres** [comment]
Yes there seems to be a problem with your setup. Or maybe SWS for Linux doesn't provide the Python ReaScript extension. I guess you should ask the SWS team for help :)

**Comment by Levitanus** [comment]
For python support of SWS it has to be compilled from source with perl script activated. Look at the SWS repository for exact info
