### ISSUE TITLE
Subclassing is unavailble

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#66]
I'm confused in quick localizing the issue and suggesting the solution.
When I received the `deferred script error` with subclassing `reapy.Project` I had checked the cache mechanic and, mainly understood what is going there. But I'm totally confused of how can it be resolved:
- mainly, I can suggest that if `importlib` arg is changed from the reapy.core to the something cacheble, it can allow to import the same classes from inside reaper.
- but I consider, that such mechanic is chosen for avoiding of losing the uncacheble data from third-party classes.
- also, a couple of times I've missed the possibility to make `inside_reaper()` work really *inside*, and, considering this, I wonder why not to pickle?
- but I also cannot notice, that reapy is much more stable than I ever been in my attempts to make Reaper respond from outside, and I feel uncomfortable to ask more...

**Comment by Levitanus** [comment]
Have a draft solution with #67

**Comment by RomeoDespres** [comment]
Discussion moved to #67 for now.

**Comment by Levitanus** [comment]
I start to doubt of the current subclassing mechanic, as it, yes, being gentle to imports, tightening hands in several cases. For example, now, projecting gui, I feel common to use user-defined methods to be called from inside for the better performance:

Here is run ought to be called by the mainloop if exists.
```Python
class Top(rpr.TopLevel):

    def run(self) -> None:
        print('run')


# root = rpr.TopLevel('my_test_window')
root = Top('my_test_window')
root.mainloop()
```

Occasionally, the class, working inside reaper is not Top, but reapy.TopLevel.

The same case for the mapping: If programmer has method, takes several API calls once that is used in cycle  — it is better to subclass core class, add custom method and then use `map` to call it without sockets connections overhead.

Maybe, we should discuss the possibility to really import what programmer wrote.
