### ISSUE TITLE
reapy GUI

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#75]
Since #74 brings c-bindings, we can discuss the possibilities for GUI.
I see 3 ways of it core:

- make bindings for JS_* functions, which would require of installing JS Rescript extension. It is the easiest way, and, since on the Win and OSX it can be installed from reapack it's not a burden for the end-user. But Linux is different at the moment: building of it is quite painful, I made it only once.
- look for the platform-independent way of painting on the window, got from the core reaper functions. It's the really painful way and I dropped the idea several times yet.
- grab the own copy of LICE(WDL) library and bind to it directly. Can't imagine how much harder it could be opposite to JS-way.

any ideas?

**Comment by Levitanus** [comment]
I've investigated a bit of possibility to wrap WDL directly and, for the moment it is easier to begin within `JS_ReaScript API` backend, then, maybe, move to reapy's own realization.
I've started wrap `JS_* API` here: https://github.com/Levitanus/reapy/tree/feature/gui

Since it consists of endless functions, any possible help is appreciated. More than, I'm confused of how to test it: I'm not only just unable to write some unit test, but, currently, I'm unable to make hand-testing of what is going on there. But the direction seems to me right and I think we can continue as I've started.

It's better to start from the end and push to the branch by little frequent portions for avoiding of our double-work.

Since the API is wrapped, the GUI structure can be thought of. :)

**Comment by Levitanus** [comment]
No need for manual wrapping, I've almost done with auto generation. But then a bit of hacks will be needed for installation. Bless Julian, he makes binaries for deployment.

**Comment by Levitanus** [comment]
JS_API introduced in #85

**Comment by Levitanus** [comment]
good news: API works fine.
bad news: I cannot make not a triffle, even can't put the window in the docker...

**Comment by Levitanus** [comment]
I'm casting: @DrewTNBD , @dimentorium , And Romeo, of course
Guys, I have major success within window management, and, I feel, the basic dockable `TopLevel` and basic `Widget` aka `Frame` will be ready.

This is the point, where our small community is need:
* When the basic architecture is ready — some work on widgets is needed, I'm not sure I'm able to make the whole core in a reasonable time by myself.
* What is more important — I'm not experienced enough in low-level GUI programming, as I came from the `KSP`. I know a bit `tkinter, kivy` and `pyqt`, but I don't really in their event model. So, I'm not exactly sure what the parent-child relations and bindings should look like. Also, I would really like to have responsive layout model close to `kivy`, but only time I've [implemented](https://github.com/Levitanus/pyksp/blob/master/pyksp/compiler/bi_ui_controls.py) layout — I copied API of `tkinter` within its limitations like exact order of declarations, manual re-mapping etc.

If one is able to make some pseudo-code, block-scheme, or fork of my gui branch to think about this — I appreciate this a lot.

Key things to think about:
* layout and coordinates:
    - how to bind
    - when to update
    - how to encapsulate
* event handling:
     - where to track (on parent, on child)
     - how to bind
     - what to do with focus (I mean, JS API allows getting input whether window is focused or not, but this is really question)
    - accessibility? This is where my brain crashed.

**Comment by Levitanus** [comment]
Today's result:

* Window can be created, event loop is established, exit cases are made: by script error, by closing the gui, by terminating script in Reaper.
* Everything works as from inside, as from outside (in case of outside, the mainloop goes inside within defer)
* basic Event tracking started: https://youtu.be/_FYy_qdGKZc

**Comment by Levitanus** [comment]
This is really exiting! For example, we can support unicode `e.g абырва́лг` keyboard input (gfx can not do this). But amount of work is stunning...

**Comment by dimentorium** [comment]
Hi Levitanus,
looks interesting! Latest in June I have two weeks off, and will spend more time on programming, but will try earlier!

**Comment by Levitanus** [comment]
Hi. I have a little update on the process. It is better to see the video: https://youtu.be/IzzMYdwE9yg

It may look not so impressing, but the showed behavior keeps noticeable amount of work:

* The managing and keeping safe windows and interactions are improved
* Event system established: now everything happens during event loop is wrapped to be accessible as from outside as from inside, whether gui classes had been subclassed by end-coder or not.
* Keyboard supports unicode and has verbose events to work with

I really like the way event loop made. For example, here is part of captured log during testing:
loop runs from outside and from inside. Outside part takes queued keyboard events from inside and fires them to the outside objects:

```
frame()
on_key_char(time=17490.50636416, char=a, mod=<vVirtKey.1: 1>)
frame()
on_key_char(time=17490.529582476, char=s, mod=<vVirtKey.1: 1>)
on_key_char(time=17490.574602799, char=d, mod=<vVirtKey.1: 1>)
frame()
on_key_char(time=17490.597725631, char=f, mod=<vVirtKey.1: 1>)
```
The code of rotating rectangle from video:
```Python
# print('start')
# from reapy.core.gui import JS_API as JS
import traceback
from sys import exc_info
from sys import stdout
try:

    from reapy import JS
    from reapy import reascript_api as RPR
    import reapy as rpr
    from time import sleep, time
    import typing as ty

    import atexit

    class Top(rpr.TopLevel):

        def setup(self) -> None:
            print('setup()')
            self.pbm = JS.VoidPtr(0)
            while int(self.pbm) == 0:
                self.pbm = JS.LICE_CreateBitmap(False, 100, 100)
                print(self.pbm)
            print(self.pbm)
            JS.LICE_GradRect(
                self.pbm, 0, 0, 100, 100, 1, 0.5, 0, 1, 1, 0.5, 0, 1, 1, .5, 0,
                1, "COPY"
            )
            self.angle = 0
            self.pngw = JS.LICE_GetWidth(self.pbm)
            self.pngh = JS.LICE_GetHeight(self.pbm)
            print(f'w, h  ={self.pngw, self.pngh}')
            self.sbm = JS.LICE_CreateBitmap(True, self.pngw, self.pngh)
            print(f'sbm: {self.sbm}')
            pOk = JS.Composite(
                self.hwnd, 0, 0, self.pngw, self.pngh, self.sbm, 0, 0,
                self.pngw, self.pngh
            )
            print('pOk: {pOk}')

        def run(self) -> None:
            # print('run()')
            win, sbm, pbm, pw, ph = (
                self.hwnd, self.sbm, self.pbm, self.pngw, self.pngh
            )
            # print(f'run(win:{win}, sbm:{sbm}, pbm:{pbm}, pw:{pw}, ph:{ph})')
            JS.LICE_Clear(sbm, 0)
            JS.LICE_RotatedBlit(
                sbm, 0, 0, pw, ph, pbm, 0, 0, pw, ph, self.angle, 0, 0, True,
                1, "COPY"
            )
            JS.Window_InvalidateRect(win, 0, 0, pw, ph, True)
            self.angle += .1
            # JS.Window_Update(win)

    # root = rpr.TopLevel('my_test_window')
    root = Top('my_test_window')
    root.mainloop()
except Exception as e:
    print(e)
    traceback.print_tb(exc_info()[2], file=stdout)
```

realted commit: https://github.com/RomeoDespres/reapy/pull/85/commits/246bdc0b806495a333c11c3a8533807347fae5d2

**Comment by DrewTNBD** [comment]
That's really cool!

**Comment by Levitanus** [comment]
Testing generic Canvas class and generic Composer. https://youtu.be/kGEcnqKEs4s
Actually, it can composite on every Reaper window, but there're some problems in getting proper handle (to not think of Z-order).

compositor animation:
```Python
def move(canv: CV, min_left: int, max_left: int) -> None:
    canv_rect = cp.bitmaps[canv.ptr]
    global direction
    if canv_rect.left >= max_left:
        direction = -5
    if canv_rect.left <= min_left:
        direction = 5
    wnd_dim = canvas.Dimentions(
        canv_rect.left + direction, 100, canv.width, canv.height
    )
    canv_dim = canvas.Dimentions(0, 0, *canv.size)
    cp.composite(canv.ptr, wnd_dim, canv_dim)
```

Canvas internal:
```Python
class CV(canvas.Canvas):

    def __init__(
        self,
        size: ty.Optional[ty.Tuple[int, int]] = None,
        ptr: ty.Optional[JS.VoidPtr] = None,
        bg_color: int = 0xff000000
    ) -> None:
        super().__init__(size, ptr, bg_color)
        self.child = canvas.Canvas(size=(10, 10), bg_color=0xff00ff00)
        self.child.draw()
        self.direction = 3
        self.c_x = 0
        self.c_a = 1.0
        self.a_step = 0.1

    @rpr.inside_reaper()
    def draw(self) -> None:
        self.c_x += self.direction
        if self.c_x + self.child.width >= self.width:
            self.direction = -3
        if self.c_x <= 0:
            self.direction = 3
        if self.c_a >= 1 or self.c_a <= 0.5:
            self.a_step = -self.a_step
        self.c_a += self.a_step

        JS.LICE_Blit(
            self.ptr, self.c_x, 20, self.child.ptr, 0, 0, *self.child.size,
            self.c_a, 'ADD'
        )
```

going to add some drawing methods )

**Comment by Levitanus** [comment]
Walter-like scaled blit (If someone familiar with "the power of pink")

At upper-right corner is original `squares.png`

In the window, left and bottom sides left with unscaled 20px, top and right — with 10px

![reapy_scaled_blit](https://user-images.githubusercontent.com/29713891/83342184-59d59900-a316-11ea-9e8b-20e15f853dde.png)

**Comment by dimentorium** [comment]
@Levitanus wanted to test your wrapper today, but it is not executing the line 
from reapy import JS

Within Reaper I installed the latest reascript API and cloned your repository that is linked above. I am using Win 10, any ideas what I might be missing?

thanks!

**Comment by Levitanus** [comment]
@dimentorium, The JS API itself should be installed.
Basically, I doubd the last commit is workung, as It goes through endless refactoring last 2 weeks.
But, anyway, You should run reapy.core.gui._JS_generator or reacripts.enable_dist_api at first. This will download and parce JS extension

**Comment by Levitanus** [comment]
I've made a snapshot of the current state of development. It has problems working outside, but looks more like finished carcass.

This is basic widget structure, you can try to draw inside something with the `widget.canvas.draw()`.
```Python
import traceback
from sys import exc_info
from sys import stdout
from time import sleep
try:
    import reapy as rpr
    from reapy.core import gui
    from reapy.core.gui import JS

    el = gui.EventLoop()
    mw = gui.Widget(window_title="main", size=gui.Size(200, 200))
    mw.canvas.bg_color = gui.Color(0xff, 0xff, 0, 0)
    el.add_child(mw)

    cw = gui.Widget(
        window_title="child1", bg_color=gui.Color(0xff, 0, 0, 0xff)
    )
    mw.add_child(cw)

    el.mainloop()

except Exception as e:
    traceback.print_tb(exc_info()[2], file=stdout)
    print(e)
```

**Comment by Levitanus** [comment]
The reason event loop now is separate structure is that it can work actually with the Reaper original windows too, as well as handle more than 1 "top-level" widgets, as well as use no widgets (just event loop). So it takes 2 more lines to initialize things but brings more of flexibility.

Spoiler: if you run Reaper from the command-line it should print mouse clicks to the console. But I've not included yet full integration of keyboard input from the first top-level realization.

**Comment by Levitanus** [comment]
Now my road map looks like:
* ensure everything works from outside (there're import leaks now)
* finish widgets focus handling:
  - investigate how keyboard focus moves from window to window
  - make it transparent and take the most part of work by the gui.
* finish layout system (currently there is only generic Layout that does nothing just placing widget to the particular point of parent)
* make support of sprite animations for images (png and jpg), as vector graphics (LICE or GDI) of the swell is almost unusable. So widgets drawing will look more or less like `Walter`. Yes, GDI drawing should look more like original Reaper `gfx.*` functions, but it has problems being cross-platform and only basics are ported by Julian now. LICE itself (bitmap-based drawing) has inconsistent API and almost unusable for complex drawing (only if You don't want to draw everything pixel by pixel).

**Comment by Levitanus** [comment]
Also, in the current implementation, I feel leak of possibility do make gui initializing declarative as `*.kv` or `simple_gui` approach.

I would like to see something like:
```Python
EventLoop()[TopLevel()[
    GridLayout()[
        [TextArea()],
        [Button("OK), Button('abort')],
        [BoxLayout(Vertical)[
            [Slider(), Button(), Menu()]
        ]]
   ]
]]```

But anyway it leads to problems of identification, which are solved by extra-typing and, still make things not as clear as desired.
Maybe there will be some ideas on that count later.

**Comment by Levitanus** [comment]
I think we can close this one as `imgui` now is the best option to use with `Python`.

This was really a challenge)))
