### ISSUE TITLE
Writing a blog on Reaper Python and Reapy

### ISSUE THREAD

**Issue by dimentorium** [RomeoDespres/reapy#89]
Hi all,
just wanted to check if no ones gets angry.
Wanted to start a small blog on this topics to help other users get Python and Reapy installed and maybe enlarge the community a bit. Are you OK with that? Until now I did not find something on that (except the Reapy doc ;-))

**Comment by RomeoDespres** [comment]
Totally ok with that of course :) On my side I've started to work on improved documentation, I'm sure both projects can be complementary. Please send us the address when it is up and running :)

**Comment by dimentorium** [comment]
Very basic and still in development, ;-)
https://raipt.wordpress.com/

**Comment by Levitanus** [comment]
Congrats)
I cannot say I never wanted to learn Deutch, but the language select button will be adorable)

**Comment by dimentorium** [comment]
Stay tuned ;-) just switched the platform, did no like Wordpress.
https://raipt.azurewebsites.net/
So here again Python rocks ;-)

**Comment by dimentorium** [comment]
Hopefully last platform switch...
https://dimentorium.wixsite.com/raipt
Added also a post on Reapy installtion
@RomeoDespres maybe you can comment if I wrote something wrong

**Comment by RomeoDespres** [comment]
Nice work! Everything seems fine to me.
