### ISSUE TITLE
Start recording through api

### ISSUE THREAD

**Issue by cspaeth** [RomeoDespres/reapy#94]
First of all - love this module, it's kind of exactly what i was looking for...  I really appreciate a project that "just works" - nicely done!

I noticed there is no method to start the recording on a project. I can play(), pause() and stop() - shouldn't there be a record() too? I mean there is CSurf_OnRecord, but having a record method in Project would be more elegant... 

Is that just not implemented, or is there another reason for not providing it? If it's an easy fix, I would be up for creating a PR.

Thanks & Cheers,
   Christian

**Comment by Levitanus** [comment]
I feel there is no native API call for record and it should be done via action `1013`.
Should be it implemented as separate  `reapy` call? Maybe, there are some hard-coded actions in the library. Let's wait for @RomeoDespres opinion)

`SCurf` API are generally not for control flow — these somehow used as callbacks and really I've never could make something useful via python, lua or eel. They are C++ callbacks.

**Comment by cspaeth** [comment]
Cool, thx - makes sense, I will use the action from now on. 

I have used CSurf_OnRecord befroe - probably not the way it is intended - but it did trigger the recording when called...

**Comment by RomeoDespres** [comment]
Thanks for the idea (and enthusiasm!). I agree it is a highly desirable feature. I've coded a `Project.record()` method using action 1013 as suggested by @Levitanus. It will be in the next release, will let you know once it's out!

**Comment by cspaeth** [comment]
Wow, thanks @RomeoDespres

**Comment by RomeoDespres** [comment]
Version 0.8.0 is out and includes the `Project.record()` method. `pip install --upgrade python-reapy` and you should be good :)
