### ISSUE TITLE
reconnect issue under Mac OS

### ISSUE THREAD

**Issue by AmrShaloudi** [RomeoDespres/reapy#96]
Hi
![Screen Shot 2020-09-29 at 10 54 33 AM](https://user-images.githubusercontent.com/55235586/94539472-f02ab480-024d-11eb-96d6-234695893c0c.png)
first of all, thanks for all your efforts making this module.. really appreciated :)
I'm using reapy to build automation flows and tests based on REAPER where I have an issue under MAC

what I noticed (see attached image) whenever REAPER get crashed for any reason like adding defect fx, I cannot continue using reapy with REAPER in the same session and many times it required to restart the OS to solve it.

under Win, I used reapy.reconnect() and all works well

any advise?
Regards

**Comment by Levitanus** [comment]
This is issue only for development cycle.
It presents after crashes as one of python sockets still works. Only thing you need to fix it — kill everything uses the socket.
Actually it should not last longer than 120 sec. 
Maybe we should have a look at the sockets building, maybe we can fix this.

**Comment by RomeoDespres** [comment]
Hi @AmrShaloudi, thanks for the report. Commit e6395e9 should fix this issue. If you are running reapy from source, you can already try it and see if it works for you. If you installed reapy from pip, I'll let you know here when the fix is published.

**Comment by AmrShaloudi** [comment]
Thanks @Levitanus for your comment. Actually killing everything use the socket will kill also my python flow which is the cause of this issue. and yeah you are right, sleep over 120 sec solved it ;)

Thanks @RomeoDespres for adding a fix. mainly I go with pip install since I'm trying to build flows over many machines but I'll test it on my private one and let you know

Regards

**Comment by RomeoDespres** [comment]
Hi @AmrShaloudi, the fix has been included in version 0.9.0. Please let me know if anything still goes wrong.
