### ISSUE TITLE
psutil requirements

### ISSUE THREAD

**Issue by chabErch** [RomeoDespres/reapy#98]
I'am trying to update reapy from 0.5 version to 0.8 and get this:

```
> pip install python-reapy
Collecting python-reapy
...
Installing collected packages: psutil, python-reapy
Running setup.py install for psutil: started
Running setup.py install for psutil: finished with status 'error'
...
... fatal error C1083: ... No such file or directory,
VisualStudio is not installed; get it from http://www.visualstudio.com/...
```

Am i doing smth wrong or i need VS to use reapy?

**Comment by RomeoDespres** [comment]
According to [psutil docs](https://github.com/giampaolo/psutil/blob/master/INSTALL.rst) and my personal tests, it looks like visual studio is needed if you install psutil from source. However if you install a binary wheel then all should be fine. Question is, why does your pip want to install from source? Is it something that you have manually set up or should we dig more to understand the problem?

**Comment by chabErch** [comment]
There are no whl version psutil for python3.9 on pypi.

I downgraded python version and the error gone
